accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

articles/urls.py
from django.urls import path,re_path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    re_path(r'(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

blackhair3000/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path(r'', article_views.article_list, name="home"),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('editor/', include('editor.urls')),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

editor/urls.py
from django.urls import path, re_path
from . import views

app_name = 'editor'

urlpatterns = [
    path('uploadImage/', views.upload_images, name="upload_image"),
    path('create/content/', views.create_content, name="create_content"),
    re_path('content/detail/(?P<src_id>[0-9]*)/$', views.display_content, name="display_content"),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default="default.png", blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

editor/models.py
from django.db import models
import jsonfield

class ArticleContent(models.Model):
    content = jsonfield.JSONField(null=True, blank=True)

articles/forms.py
from django.forms import ModelForm
from . import models

class CreateArticle(ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb', ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.

def signup_view(request):

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()

    return render(request, "accounts/login.html", {'form': form})


def logout_view(request):

    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)

    return render(request, 'articles/article_detail.html', {'articles': article})


@login_required(login_url="/accounts/login")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/create_article.html', {'form': form })

blackhair3000/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

editor/views.py
import json
import os
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.conf import settings
from .models import ArticleContent
from django.http import HttpResponseRedirect
from django.urls import reverse

def handle_uploaded_file(f):
    print("f:", f.name)
    with open(os.path.join(settings.MEDIA_ROOT, 'images/{0}'.format(f.name)), 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

    return f.name, f.size


def upload_images(request):
    if request.method == 'POST':
        image_name, image_size = handle_uploaded_file(request.FILES['image'])
        return JsonResponse(
            {'file': {'url': '/media/images/{0}'.format(image_name), 'name': image_name, 'size': image_size},
             'success': 1}, safe=False)


def create_content(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        print(data)

        ac = ArticleContent()
        ac.content = data
        ac.save()

        print("src_result",ac.id)

        return JsonResponse({"message":"successful", "url":"/", "status":"201", "src_id":ac.id})

        # return HttpResponseRedirect(reverse("editor:display_content"))

        # return render(request, 'editor/content_detail.html', {'article_content': ac})


    if request.method == 'GET':
        print("this is editor get")
        return render(request, 'editor/create_content.html', {"message": "successful", "url": "/", "status": "200"})


def display_content(request, src_id=1):

    if request.method =='POST':
        print("wwwwwwwwwwwwwwwww")
        return render(request, 'editor/content_detail.html', {})
        # article = ArticleContent.objects.filter(content__contains={'time':c_time})
        # article_content = get_object_or_404(ArticleContent, pk=src_id)
        # print("article_content query",article_content)

    else:
        print("hahahahahah")
        article_content = get_object_or_404(ArticleContent, pk=src_id)
        return render(request, 'editor/content_detail.html')


def display_contents(request):
    if request.method == 'GET':
        article_content = ArticleContent.objects.all()
        return render(request, 'articles/article_list.html', {'articles': article_content})
    else:
        pass

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next}}">
        {% endif %}
        <input type="submit" value="Login">

    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">

    </form>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}"/>
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>article list</h1>

<div class="articles">
    {% for article in articles %}
    <div class="article">
        <h2>
            <a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a>
        </h2>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">added by {{ article.author.username }}</p>

    </div>
    {% endfor %}

</div>
{% endblock %}

articles/templates/articles/create_article.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-article">
    <h2>Create article</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
</div>

<script src="/static/slugify.js"></script>

{% endblock %}

editor/templates/editor/content_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

editor/templates/editor/create_content.html
{% extends 'base_layout.html' %}

{% block content %}

    <h1>Your content</h1>
    <div id="editorjs"></div>
    <button id="save-button">Save</button>
    <pre id="output"></pre>
    <script src="/static/slugify.js"></script>
    <script src="/static/editor.js"></script>
    <script src="/static/header.js"></script>
    <script src="/static/list.js"></script>
    <script src="/static/image.js"></script>
    <script src="/static/jquery-3.4.1.min.js"></script>
    <script src="/static/paragraph.js"></script>

    <script>

        const editor = new EditorJS({
            /**
             * Id of Element that should contain the Editor
             */
            autofocus: true,
            holder: 'editorjs',
            tools: {
                header: {
                    class: Header,
                    inlineToolbar: true
                },
                list: {
                    class: List,
                    inlineToolbar: true,
                    shortcut: 'CMD+SHIFT+L'
                },
                image: {
                    class: ImageTool,
                    config: {
                        endpoints: {
                            byFile: "{% url 'editor:upload_image' %}",
                        },
                        additionalRequestHeaders: {"X-CSRFToken": '{{ csrf_token }}'},
                        additionalRequestData: {},
                        field: "image",

                    }
                }

            },
        });

        const saveButton = document.getElementById('save-button');
        const output = document.getElementById('output');


        saveButton.addEventListener('click', () => {
            editor.save().then(savedData => {
                output.innerHTML = JSON.stringify(savedData, null, 4);

                console.log('Article data: ', savedData)

                $.ajax({
                    headers: {"X-CSRFToken": '{{ csrf_token }}'},
                    type: 'POST',       // define the type of HTTP verb we want to use (POST for our form)
                    url: "/editor/create/content/",
                    encode: true,
                    contentType: 'application/x-www-form-urlencoded',
                    crossDomain: false,
                    dataType: 'json',
                    data: JSON.stringify(savedData, null, 4),     // our data object
                    success: function (data) {
                        {#                location.reload();#}

                        console.log('successful')

                        window.location="/editor/content/detail/"+data.src_id+"/"

                    },
                    error: function (exception) {
                        alert('create error');
                    }
                });


            })
        })


    </script>


{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>about</title>
</head>
<body>
    <h1>About us</h1>
    <p>this is about page</p>
</body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_list</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header class="wrapper">
        <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="logo.png"></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout'%}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create' %}">New Article</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>

        </nav>
    </header>

    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>homepage</title>
</head>
<body>
    <h1>home page</h1>
    <p>this is home page</p>
</body>
</html>